// <auto-generated />
namespace CPS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class request_int_long : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(request_int_long));
        
        string IMigrationMetadata.Id
        {
            get { return "201611301026111_request_int_long"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
