// <auto-generated />
namespace CPS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Reques_Changed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Reques_Changed));
        
        string IMigrationMetadata.Id
        {
            get { return "201607270424511_Reques_Changed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
